name: Staging Area

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "staging" branch
  push:
    branches: [ "staging" ]
  pull_request:
    branches: [ "staging" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  tests_and_model_training:  # Fixed the job name to be valid
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

     # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      
      - name: Install essential dependencies
        run: pip install --upgrade pip setuptools wheel

      - name: Install dependencies
        run: pip install -r backend/classification/requirements.txt

      - name: Set PYTHONPATH and run tests
        run: |
          export PYTHONPATH=${GITHUB_WORKSPACE}/backend
          pytest 
        working-directory: backend/classification/

  tests_and_flask_backend:  # Fixed the job name to be valid
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

     # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      
      - name: Install essential dependencies
        run: pip install --upgrade pip setuptools wheel

      - name: Install dependencies
        run: |
          pip install -r backend/class_api/requirements.txt

      - name: Set PYTHONPATH and run tests
        run: |
          export PYTHONPATH=${GITHUB_WORKSPACE}/backend
          pytest 
        working-directory: backend/class_api/
  
  Push_to_production_branch:
    needs: [tests_and_model_training, tests_and_flask_backend]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git
      - uses: fregante/setup-git-token@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge Staging to Production and Push
        run: |
          git fetch origin
          git checkout production
          git pull origin production  
          git merge staging  # Merge `staging` into `production`
          git push origin production 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}





