name: Staging Area

on:
  push:
    branches: [ "staging" ]
  pull_request:
    branches: [ "staging" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  tests_and_model_training:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r backend/classification/requirements.txt

      - name: Run tests
        run: |
          export PYTHONPATH=${GITHUB_WORKSPACE}/backend
          pytest 
        working-directory: backend/classification/

  tests_and_flask_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r backend/class_api/requirements.txt

      - name: Run tests
        run: |
          export PYTHONPATH=${GITHUB_WORKSPACE}/backend
          pytest 
        working-directory: backend/class_api/

  Push_to_production_branch:
    needs: [tests_and_model_training, tests_and_flask_backend]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Merge Staging to Production
        run: |
          git checkout production
          git pull origin production  
          git merge staging
          git push origin production
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}