name: Staging Area

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "staging" branch
  push:
    branches: [ "staging" ]
  pull_request:
    branches: [ "staging" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  tests_and_model_training:  # Fixed the job name to be valid
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4

      # Install dependencies from the requirements.txt for model training and testing
      - name: Install dependencies for model training and testing
        run: pip install -r requirements.txt


      # Run pytest for the test cases
      - name: Run pytest for tests
        working-directory: backend
        run: |
          pytest /classification/test/
